# Generated by Django 4.2 on 2023-05-03 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('money', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('character', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='character.character')),
            ],
            options={
                'ordering': ['-money'],
            },
        ),
    ]
