# Generated by Django 4.1.7 on 2023-05-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_character'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_on']},
        ),
    ]
