# Generated by Django 4.1.7 on 2023-06-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
