# Generated by Django 4.2 on 2023-05-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
