# Generated by Django 4.2 on 2023-05-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_alter_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
