# Generated by Django 4.1.7 on 2023-05-10 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_character_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='last_log',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 10, 5, 56, 26, 741713)),
        ),
    ]
