# Generated by Django 4.1.7 on 2023-05-16 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_alter_character_last_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='last_log',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 16, 10, 25, 35, 316082)),
        ),
    ]
