# Generated by Django 4.1.7 on 2023-06-07 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_alter_character_last_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_log',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 7, 9, 58, 10, 981342)),
        ),
    ]
