# Generated by Django 4.1.7 on 2023-06-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_character_avatar_alter_character_last_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='last_log',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
