# Generated by Django 4.1.7 on 2023-06-12 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_alter_character_last_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_log',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
