# Generated by Django 4.2 on 2023-05-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
